# Generated by Django 4.1.1 on 2022-11-20 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="categoria_Servicio",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("correo", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_emision", models.DateTimeField()),
                (
                    "id_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Modelo.cliente"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
                ("ruc", models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name="Locacion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ciudad", models.CharField(max_length=15)),
                ("provincia", models.CharField(max_length=15)),
                ("distrito", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("monto_total", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                    ),
                ),
                (
                    "id_contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Modelo.contrato",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Postal",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("numero", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Servicio",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                (
                    "id_categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Modelo.categoria_servicio",
                    ),
                ),
                (
                    "id_empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Modelo.empresa"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Telefono",
            fields=[
                (
                    "numero",
                    models.CharField(
                        max_length=9, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=16, unique=True)),
                ("contrasena", models.CharField(max_length=16)),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("CLIENT", "Client"),
                            ("GERENT", "Gerent"),
                        ],
                        default="CLIENT",
                        max_length=16,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaccion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                    ),
                ),
                ("detalle", models.TextField()),
                (
                    "id_pago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Modelo.pago"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Solicitud",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INICIADO", "Iniciado"),
                            ("PENDIENTE", "Pendiente"),
                            ("EN PROCESO", "En Proceso"),
                            ("CANCELADO", "Cancelado"),
                            ("APROBADO", "Aprobado"),
                        ],
                        default="INICIADO",
                        max_length=15,
                    ),
                ),
                (
                    "id_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Modelo.cliente"
                    ),
                ),
                (
                    "id_servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Modelo.servicio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="servicio_Postal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_postal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Modelo.postal"
                    ),
                ),
                (
                    "id_servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Modelo.servicio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="servicio_Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Modelo.empresa"
                    ),
                ),
                (
                    "id_servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Modelo.servicio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gerente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("correo", models.EmailField(max_length=254)),
                (
                    "id_empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Modelo.empresa"
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Modelo.usuario"
                    ),
                ),
                (
                    "telefono",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Modelo.telefono",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="empresa",
            name="id_locacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Modelo.locacion"
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="telefono",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Modelo.telefono"
            ),
        ),
        migrations.CreateModel(
            name="detalle_Contrato",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField()),
                ("detalle", models.TextField(default="Ninguno")),
                (
                    "id_contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Modelo.contrato",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contrato",
            name="id_servicio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Modelo.servicio"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="id_locacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Modelo.locacion"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="id_usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Modelo.usuario"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="telefono",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Modelo.telefono"
            ),
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Modelo.usuario"
                    ),
                ),
            ],
        ),
    ]
