# Generated by Django 4.1.1 on 2022-11-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Modelo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalle_contrato", name="detalle", field=models.TextField(),
        ),
    ]
